[settings]
experimental = true
env_shell_expand = true
task.show_full_cmd = true

[env]
_.file = [".env", ".env.local"]

[tools]
npm = "latest"
node = "lts"
go = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
awscli = "latest"
doctl = "latest"
terraform = "1.14.3"
kubectl = "latest"
kubeseal = "latest"
cmctl = "latest"
k9s = "latest"
gh = "latest"
