[env]
_.path = ["{{ config_root }}/node_modules/.bin"]

[tools]
"go:seahax.com/go/s3upload" = "latest"

[tasks.start]
run = '''
vite dev
'''

[tasks.test]
run = '''
tsc -b -f tsconfig.build.json
eslint src --max-warnings=0
vitest run
'''

[tasks.build]
run = '''
vite build
'''

[tasks.publish]
description = "Deploy home frontend to CDN"
env.BUCKET = "cdn--seahax-194722422414"
env.DISTRIBUTION = "E2UQKRZMWSCWZ"
run = [
  { task = "build" },
  { task = "test" },
  '''
  s3upload -root dist -bucket "$BUCKET" \
    -i '^assets/' \
    -cache-control 'public, max-age=31536000, immutable'
  echo
  s3upload -root dist -bucket "$BUCKET" \
    -e '^assets/' -e '(^|/)tsbuildinfo$' \
    -cache-control 'public, max-age=60, stale-while-revalidate=2592000'
  echo
  aws cloudfront create-invalidation \
    --distribution-id "$DISTRIBUTION" \
    --paths "/index.html"
  '''
]
