[env]
_.file = [".env", ".env.local"]

[tasks.start]
run = [
  { task = "build" },
  '''
export APP_COMMIT=development
export APP_BUILD_TIMESTAMP=$(date +%s)
docker-compose up --remove-orphans --no-attach mongo
'''
]

[tasks.build]
env.GOOS = "linux"
env.GOARCH = "amd64"
env.CGO_ENABLED = 0
run = '''
mkdir -p out
echo "$(date '+v%Y.%m.%d-at-%H%M%S')" > out/version
rm -rf dist/*
go build -o dist/api-service .
'''

[tasks.build-image]
run = [
  { task = "build" },
  '''
docker build --no-cache --progress=plain \
  --platform linux/amd64 \
  --build-arg APP_COMMIT="$(git rev-parse --short HEAD)" \
  --build-arg APP_BUILD_TIMESTAMP="$(date +%s)" \
  -t ghcr.io/seahax/api:latest \
  -t ghcr.io/seahax/api:$(cat out/version) \
  .
'''
]

[tasks.push-image]
run = [
  { task = "build-image" },
  '''
docker login ghcr.io -u seahax --password "${GITHUB_TOKEN}"
docker push ghcr.io/seahax/api:$(cat out/version)
docker push ghcr.io/seahax/api:latest
'''
]
